sudo: false
language: node_js
node_js:
  - stable
sudo: false
services:
  - docker
before_install:
  - docker build -t bryantop/rwbypandaportfolio .
  - docker run bryantop/rwbypandaportfolio
deploy:
  edge: true
  provider: heroku
  api_key:
    secure: "dfeddd7c-a223-4f3f-b1d6-9ee8dd15e6d9"